# Generated by Django 4.0.5 on 2022-07-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'Male')], max_length=6)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=20)),
                ('language', models.CharField(choices=[('chinese', 'Chinese'), ('english', 'English'), ('nepali', 'Nepali')], max_length=50)),
                ('country', models.CharField(choices=[('nepal', 'Nepal'), ('china', 'China'), ('usa', 'USA')], max_length=10)),
                ('image', models.ImageField(upload_to='students')),
            ],
        ),
    ]
