# Generated by Django 4.0.5 on 2022-07-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_student_country_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students'),
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('chinese', 'Chinese'), ('nepali', 'Nepali')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
