# Generated by Django 4.0.5 on 2022-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_student_country_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(choices=[('nepal', 'Nepal'), ('china', 'China'), ('usa', 'USA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('chinese', 'Chinese'), ('english', 'English'), ('nepali', 'Nepali')], max_length=50),
        ),
    ]
